FLASK_APP=app.py

FLASK_DEBUG=true
FLASK_TEST=true
FLASK_ENV=development

LOGGER_HANDLER_POLICY=debug
LOGGER_NAME=femmapi

SECRET_KEY=KEY
JWT_SECRET_KEY=KEY2

JWT_BLACKLIST_ENABLED=true
JWT_BLACKLIST_TOKEN_CHECKS=true

DATABASE_URL=postgresql+psycopg2://postgres:dev-server@172.18.0.2
SQLALCHEMY_TRACK_MODIFICATIONS=false

MAX_SEARCH_RESULT=50
MAX_PAGINATION=5